package io.github.quafadas.scautable

import io.github.quafadas.table.*
import org.apache.poi.ss.formula.functions.Fixed

class FixedWidthResourceSuite extends munit.FunSuite {

  test("Fixed Width") {
    val data: FixedWidthIterator[("h3", "h2", "h4", "hhh"), (Double, Int, String, Int)] = FixedWidth.resource("fixed_width.csv")

    val rows = data.toList
    assertEquals(rows.length, 3)


    val first = rows.head
    assertEquals(first.h3, 1.0)
    assertEquals(first.h2, 38)
    assertEquals(first.h4, "ss")
    assertEquals(first.hhh, 64)

    val second = rows(1)
    assertEquals(second.h3, 0.0)
    assertEquals(second.h2, 64)
    assertEquals(second.h4, "ssss")
    assertEquals(second.hhh, 23)
  }

  test("no header"){

    val data: FixedWidthIterator[("col_0", "col_1", "col_2"), (String, Int, String)] = FixedWidth.resource(
      "simple_fixed_no_header.txt",
      FixedWidthOpts(
        HeaderOptions.AutoGenerated
      )
    )

    val rows = data.toList
    assertEquals(rows.length, 3)

    val first = rows.head
    assertEquals(first.col_0, "Alice")
    assertEquals(first.col_1, 30)
    assertEquals(first.col_2, "NYC")
  }

  test("FixedWidth.resource with type inference") {
    val data = FixedWidth.resource(
      "simple_fixed.txt",
      FixedWidthOpts(
        HeaderOptions.FromRows(1, 0),
        TypeInferrer.FromAllRows,
        true,
        ' '
      )
    )

    val rows = data.toList
    assertEquals(rows.length, 3)

    val first = rows.head
    assertEquals(first.name, "Alice")
    assertEquals(first.age, 30)
    assertEquals(first.city, "NYC")

    val second = rows(1)
    assertEquals(second.name, "Bob")
    assertEquals(second.age, 25)
    assertEquals(second.city, "LA")
  }

  test("FixedWidth.resource with StringType inference") {
    val data = FixedWidth.resource(
      "simple_fixed.txt",
      FixedWidthOpts(
        HeaderOptions.FromRows(1, 0),
        TypeInferrer.StringType,
        true,
        ' '
      )
    )

    val rows = data.toList
    assertEquals(rows.length, 3)

    val first = rows.head
    assertEquals(first.name, "Alice")
    assertEquals(first.age, "30")  // StringType keeps as String
    assertEquals(first.city, "NYC")
  }

  test("FixedWidth.resource with no trimming") {
    val data = FixedWidth.resource(
      "simple_fixed.txt",
      FixedWidthOpts(
        HeaderOptions.FromRows(1, 0),
        TypeInferrer.FromAllRows,
        false,  // no trimming
        ' '
      )
    )

    val rows = data.toList
    val first = rows.head

    // Without trimming, should have trailing spaces where they exist in the file
    assertEquals(first.name, "Alice     ", "name should have 5 trailing spaces")
    assertEquals(first.age, 30.0, "age should be Double (untrimmed values inferred as Double)")
    // NYC has no trailing spaces in the file, so it's just "NYC"
    assertEquals(first.city, "NYC", "city is just 'NYC' with no padding in the file")
  }

  test("FixedWidth.resource with default padding char") {
    val data = FixedWidth.resource(
      "simple_fixed.txt",
      FixedWidthOpts(
        HeaderOptions.FromRows(1, 0),
        TypeInferrer.FromAllRows,
        true,
        ' '
      )
    )

    val rows = data.toList
    assertEquals(rows.length, 3)
  }
}
