// //> using repository "jitpack"
//> using lib "org.scalameta::munit::1.0.0-M7"
//> using lib "com.lihaoyi::scalatags::0.12.0"
//> using lib "com.lihaoyi::os-lib:0.9.1"
// //> using lib "sh.almond:scala-kernel-api_2.13.10:0.13.4"
